name: Build
on:
  push:
    tags:        
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish (Linux)
      run: dotnet publish --runtime linux-x64 --no-self-contained -c Release
    - name: Publish (Windows)
      run: dotnet publish --runtime win-x64 --no-self-contained -c Release
    - name: Package (Linux)
      run: cd out-linux-x64 && tar -czf assetto-server-linux-x64.tar.gz * && cd ..
    - name: Package (Windows)
      run: cd out-win-x64 && zip -r assetto-server-win-x64.zip * && cd ..
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: |
          out-linux-x64/assetto-server-linux-x64.tar.gz
          out-win-x64/assetto-server-win-x64.zip
